#!/usr/bin/env bash

# Options
IMAGE=lzlarryli/git
NAME=fenics-git
SHAREDDIR=$PWD/shared


# Tell script to exit on first error
trap 'exit' ERR

# Test if docker is installed
if ! hash docker 2>/dev/null; then
    echo >&2 "Command 'docker' cannot be found in your system. "
    echo >&2 "Instructions for installing docker on most platforms can be found at:"
    echo >&2 "          https://docs.docker.com/"
    echo >&2 "Aborting."
    exit 1
fi

# Prepare the shared folder for the first run
if [[ ! -d $SHAREDDIR ]]; then
    cp -a ./src/default_shared_git $SHAREDDIR
fi

start_gui () {
    # Start xhost sharing
    xhost +local: >/dev/null 2>&1
    # Run docker
    docker run -i -t --rm \
           -e DISPLAY=$DISPLAY \
           -u fenics \
           -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
           -v $SHAREDDIR:/home/fenics/ \
           -w="/home/fenics" \
           --name=$NAME $IMAGE \
           xterm 
    # End xhost sharing
    xhost - >/dev/null 2>&1
}

start_cli () {
    # Run docker
    docker run -i -t --rm \
           -u fenics \
           -v $SHAREDDIR:/home/fenics/ \
           -w="/home/fenics" \
           --name=$NAME $IMAGE \
           /bin/bash
}

# parse arguments
if [ "$1" = "-c" ]; then
    start_cli
else
    start_gui
fi

